services:
  db:
    image: postgres:18-alpine
    container_name: ctf_db
    restart: always
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ctfpad
    volumes:
      - ./db_data:/var/lib/postgresql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    networks:
      - backend_network
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctf -d ctfpad"]
      interval: 5s
      timeout: 3s
      retries: 15

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    image: ctf_backend
    container_name: ctf_backend
    restart: always
    environment:
      DATABASE_URL: postgres://ctf:mysecretpassword@db:5432/ctfpad
      RUST_LOG: info,tower_http=info
      # optional: if your app supports it
      APP_ADDR: 0.0.0.0:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: ctf_frontend
    container_name: ctf_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
